# Pydantic Schemas module
from src.schemas.base import BaseSchema, TimestampSchema, PaginationParams, PaginatedResponse
from src.schemas.company import (
    CompanyCreate,
    CompanyUpdate,
    CompanyResponse,
    CompanyListResponse,
)
from src.schemas.contact import (
    ContactCreate,
    ContactUpdate,
    ContactResponse,
    ContactListResponse,
    ContactSearchResult,
)
from src.schemas.campaign import (
    CampaignCreate,
    CampaignUpdate,
    CampaignResponse,
    CampaignListResponse,
)
from src.schemas.lead import (
    LeadCreate,
    LeadCreateFromForm,
    LeadUpdate,
    LeadImportRow,
    LeadImportResult,
    LeadResponse,
    LeadListResponse,
)
from src.schemas.task import (
    TaskCreate,
    TaskUpdate,
    TaskComplete,
    TaskResponse,
    TaskListResponse,
)
from src.schemas.contact_history import (
    ContactHistoryResponse,
    NoteCreate,
    CallCreate,
)
from src.schemas.email_template import (
    EmailTemplateCreate,
    EmailTemplateUpdate,
    EmailTemplateResponse,
    EmailSend,
    EmailPreview,
    EmailPreviewResponse,
)
from src.schemas.setting import (
    SettingCreate,
    SettingUpdate,
    SettingResponse,
    LookupValueCreate,
    LookupValueUpdate,
    LookupValueResponse,
    LOOKUP_CATEGORIES,
)
from src.schemas.opportunity import (
    OpportunityCreate,
    OpportunityCreateFromLead,
    OpportunityUpdate,
    OpportunityClose,
    OpportunityResponse,
    OpportunityListResponse,
    PipelineStageStats,
    PipelineStats,
)

__all__ = [
    "BaseSchema",
    "TimestampSchema",
    "PaginationParams",
    "PaginatedResponse",
    "CompanyCreate",
    "CompanyUpdate",
    "CompanyResponse",
    "CompanyListResponse",
    "ContactCreate",
    "ContactUpdate",
    "ContactResponse",
    "ContactListResponse",
    "ContactSearchResult",
    "CampaignCreate",
    "CampaignUpdate",
    "CampaignResponse",
    "CampaignListResponse",
    "LeadCreate",
    "LeadCreateFromForm",
    "LeadUpdate",
    "LeadImportRow",
    "LeadImportResult",
    "LeadResponse",
    "LeadListResponse",
    "TaskCreate",
    "TaskUpdate",
    "TaskComplete",
    "TaskResponse",
    "TaskListResponse",
    "ContactHistoryResponse",
    "NoteCreate",
    "CallCreate",
    "EmailTemplateCreate",
    "EmailTemplateUpdate",
    "EmailTemplateResponse",
    "EmailSend",
    "EmailPreview",
    "EmailPreviewResponse",
    "SettingCreate",
    "SettingUpdate",
    "SettingResponse",
    "LookupValueCreate",
    "LookupValueUpdate",
    "LookupValueResponse",
    "LOOKUP_CATEGORIES",
    "OpportunityCreate",
    "OpportunityCreateFromLead",
    "OpportunityUpdate",
    "OpportunityClose",
    "OpportunityResponse",
    "OpportunityListResponse",
    "PipelineStageStats",
    "PipelineStats",
]
